# Generated by Django 2.1 on 2018-08-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_change_rating_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='company',
            field=models.CharField(max_length=100),
        ),
    ]
